ARG REG
ARG PREFIX_NAME
FROM ${REG}/${PREFIX_NAME}base:edge
ARG REPO_URL
LABEL org.opencontainers.image.source ${REPO_URL}

# The Go image doesn't need anything else.
# Use fnproject/go:dev to build.
